#[derive(Clone, Debug)]
pub(crate) struct Snapshot {
    pub(crate) hotkey_label: &'static str,
    pub(crate) backend_label: &'static str,
    pub(crate) is_hotkey_down: bool,
    pub(crate) popup_open: bool,
    pub(crate) status: String,
    pub(crate) stt_state_label: &'static str,
    pub(crate) stt_worker_ready: bool,
    pub(crate) stt_recorder_available: bool,
    pub(crate) stt_transcript: String,
    pub(crate) stt_status: String,
    pub(crate) stt_model_can_download: bool,
    pub(crate) stt_model_downloading: bool,
    pub(crate) stt_model_download_files_percent: f32,
    pub(crate) stt_model_download_files_label: String,
    pub(crate) stt_model_download_file_percent: f32,
    pub(crate) stt_model_download_file_known: bool,
    pub(crate) stt_model_download_file_label: String,
    pub(crate) stt_model_dir: String,
    pub(crate) stt_config_path: String,
    pub(crate) stt_use_gpu: bool,
    pub(crate) stt_auto_mute_speakers: bool,
}
